.PHONY: clean All

All:
	@echo "----------Building project:[ dodgegame - Debug ]----------"
	@cd "dodgegame" && "$(MAKE)" -f  "dodgegame.mk"
clean:
	@echo "----------Cleaning project:[ dodgegame - Debug ]----------"
	@cd "dodgegame" && "$(MAKE)" -f  "dodgegame.mk" clean
