.PHONY: clean All

All:
	@echo "----------Building project:[ w3o4 - Debug ]----------"
	@cd "w3o4" && "$(MAKE)" -f  "w3o4.mk"
clean:
	@echo "----------Cleaning project:[ w3o4 - Debug ]----------"
	@cd "w3o4" && "$(MAKE)" -f  "w3o4.mk" clean
