.PHONY: clean All

All:
	@echo "----------Building project:[ w2o5 - Debug ]----------"
	@cd "w2o5" && "$(MAKE)" -f  "w2o5.mk"
clean:
	@echo "----------Cleaning project:[ w2o5 - Debug ]----------"
	@cd "w2o5" && "$(MAKE)" -f  "w2o5.mk" clean
