.PHONY: clean All

All:
	@echo "----------Building project:[ w5o2 - Debug ]----------"
	@cd "w5o2" && "$(MAKE)" -f  "w5o2.mk"
clean:
	@echo "----------Cleaning project:[ w5o2 - Debug ]----------"
	@cd "w5o2" && "$(MAKE)" -f  "w5o2.mk" clean
