.PHONY: clean All

All:
	@echo "----------Building project:[ w3o3 - Debug ]----------"
	@cd "w3o3" && "$(MAKE)" -f  "w3o3.mk"
clean:
	@echo "----------Cleaning project:[ w3o3 - Debug ]----------"
	@cd "w3o3" && "$(MAKE)" -f  "w3o3.mk" clean
